### ISSUE TITLE
Connectivity check fails Fedora

### ISSUE THREAD

**Issue by dev-uhuru** [NordSecurity/nordvpn-linux#13]
Hello,

As title says, with nordlynx protocol, the connectivity check on Fedora (37) fails. It shows with a question mark inside of the wifi symbol in the status bar. 

This is kept in /usr/lib/NetworkManager/conf.d/20-connectivity-fedora.conf and contains:

Enable connectivity checking for NetworkManager.
 See man NetworkManager.conf.

Note that connectivity checking works badly with rp_filter set to
 strict. Check "/proc/sys/net/ipv4/conf/*/rp_filter".
[connectivity]
enabled=true
uri=http://fedoraproject.org/static/hotspot.txt
response=OK
interval=300

Setting enabled=false will get rid of the check (and the question mark). I guess the check does not go through wireguard. I have not been able to check with openvpn technology due to the other bug recorded on Fedora

It seems to be because rp_filter is set to "2" which I guess is "strict"

Thanks open sourcing it!

**Comment by dev-uhuru** [comment]
Hi, it may be related but not certain. 

I have never had to connect to a hotspot since I installed Fedora. As far as I understand it, the connectivity check is done so that the system can detect whether or not it's behind a captive portal and so, presumably, it may not detect it properly. 

I think that it would be useful to have feedback from other Linux OS.

**Comment by bjlockie** [comment]
I don't see any problem.
The wifi icon in the taskbar shows the sign strength of my local network.
The connection information shows the wifi adapter connected to "garlic" and nordlynx.
lubuntu-22.10 with the 6.2.7 kernel:
![image](https://user-images.githubusercontent.com/303873/227733692-ca56c262-6e59-4398-9012-6241c69e4d07.png)

**Comment by dev-uhuru** [comment]
Hi, thanks! I'm not sure that it will show a graphical indication if there is an issue, but another way to check is to type in "nmcli networking connectivity check" which shows "limited" when connected to NordVPN instead of "full" otherwise.

**Comment by bartoszWojciechO** [comment]
Hi, I did a little digging. It seems like NetworkManager will skip connectivity checks for interfaces that have no global routes configured. So most likely it will run a connectivity check only against your default interface, which will fail because it is blocked by the app after you enable nordlynx.

As a part of configuration, a `nordlynx` interface is added. It has connectivity, but there is no global route from it(it is not even present in the routing table), so NetworkManager will ignore it when running connectivity check. There is no option to force NM to make a connectivity check for a particular interface, so the best option would be to just disable it entirely.
