### ISSUE TITLE
nordvpn autoconnect does not work

### ISSUE THREAD

**Issue by tm4ig** [NordSecurity/nordvpn-linux#159]
nordvpn autoconnect does not work

For examle I use nordvpn set autoconnect enable Germany
After system restart I have 
Nov 11 11:30:05 nordvpnd[615]: 2023/11/11 11:30:05 [Error] picking servers: The specified server does not exist.
Nov 11 11:30:05 nordvpnd[615]: 2023/11/11 11:30:05 [Error] err1: <nil> | err2: The specified server does not exist.
Nov 11 11:30:05 nordvpnd[615]: 2023/11/11 11:30:05 [Warning] will retry( 8 ) auto-connect after: 35s

my env:
NordVPN Version 3.16.7
Ubuntu 22.04.3 LTS
Linux 5.15.0-88-generic

nordvpn settings
Technology: NORDLYNX
Firewall: disabled
Firewall Mark: 0xe1f1
Routing: enabled
Analytics: disabled
Kill Switch: disabled
Threat Protection Lite: disabled
Notify: disabled
Auto-connect: disabled
IPv6: disabled
Meshnet: disabled
DNS: disabled
LAN Discovery: disabled
Allowlisted ports:
80 (TCP)
443 (TCP)
Allowlisted subnets:

**Comment by ggediminass** [comment]
Hello,

Thank you for reaching out to us!

Unfortunately, we could not reproduce the issue you are having with our application right away.

May we ask, if you have tried to reach out to our Customer Support, in order to troubleshoot this issue?

If not, you can do so by visiting the following link:
https://nordvpn.com/contact-us

Troubleshooting issue together with Customer Support will help us to reduce the scope of the issue, or solve it.

If the issue persists, let us know!

**Comment by ggediminass** [comment]
Hello,

Since this issue was posted long time ago, and there were no further response from your side, we are closing it, as we assume, that issue was solved.

In case issue still persists, please reply here.
