### ISSUE TITLE
which ports do i need to open for meshnet to work

### ISSUE THREAD

**Issue by sehdorn** [NordSecurity/nordvpn-linux#18]
Hi there,
i am trying to run meshnet on a debian which runs iptables that blocks everything that is not explicitly allowed. That way, i am not able to connect my other devices via meshnet with the meshnet server running on my debian (expectable). Could you tell me, which port i do have to open for the subnet meshnet is using? 

thx

**Comment by Jauler** [comment]
Hi,

Due to peer-to-peer nature of the meshnet - not all ports used by the meshnet is static.

There are several services/destinations which are used in order to form the connections between peers:
* We need API access which is on `443/tcp` port
* All meshnet connections start by using cluster of relay services. While I cannot give you strong guarantees that this will never change in the future, currently `8765/tcp` is used for this cluster.
* In order get advantage of peer-to-peer connection one needs to open up STUN ports `3478/udp` and `3479/udp`. But that is not all, as peers try to communicate directly between each other using [UDP-hole punching](https://en.wikipedia.org/wiki/UDP_hole_punching) and [UPnP](https://www.rfc-editor.org/rfc/rfc6970), allocation of these ports is left to be done for the OS and is not fixed.

So depending whether one prefers peer-to-peer connections or stricter firewall - there are two options:
* Open API and relays only, in this configuration peer-to-peer connections are not available
* Open API and then allow _connections_ for packets which has fwmark value of `0xe1f1` (see mark and connmark section in [iptables(8)](https://linux.die.net/man/8/iptables))

**Comment by Savolro** [comment]
Closing as question is answered and no follow-up questions are asked
