### ISSUE TITLE
what ports should be allowed in firewall for nordvpn nordlynx work in linux?

### ISSUE THREAD

**Issue by tm4ig** [NordSecurity/nordvpn-linux#184]
what ports (source and destination) should be allowed in firewall for nordvpn nordlynx work in linux?

**Comment by mariusSincovici** [comment]
Hi,
The application uses multiple ports, majority are dynamic and only one is fixed(at least for now `51820`).
Because of this, the best approach would be to whitelist base on the `fwmark`(`0xe1f1`). In this way all the connections created by the nordvpn application would not be blocked by the firewall.

**Comment by tm4ig** [comment]
Thx for you answer
