### ISSUE TITLE
Can no longer connect from containers

### ISSUE THREAD

**Issue by leogaggl** [NordSecurity/nordvpn-linux#30]
I suddenly have a problem with NordVPN not connecting in several containers (or virtual machines). The latest NordVPN v3.16.3 and login works fine with token on all these containers. But will not connect (I tried several nodes).

`Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.`

It appears as if this is a wider problem since I have it both on a Debian Bullseye Crostini LXD running on a Chromebook as well as a couple Ubuntu 22.04 Docker containers. NordVPN has been working on both of those

The Ubuntu 22.04 host system on the same network continues to work fine.

Tried both technologies
- nordvpn set technology OpenVPN (both TCP and UDP)
- nordvpn set technology NordLynx

Attached daemonlog:
[daemonlog.txt](https://github.com/NordSecurity/nordvpn-linux/files/11711706/daemonlog.txt)

**Comment by Savolro** [comment]
Hi and thank you for reporting! Could you please provide us more information on reproduction? Hopefully this will give us some insights on where the problem may be.

- Is LXD on chromebook the only VM you are having this problem on? If no, any info on VM managers, images you are using and so on?
- Are your docker containers executed on the ubuntu 22.04 host system you mentioned? Is it x86_64?
- What command are you using to start docker containers?
- Which environment is the current `daemonlog.txt` from?
- Could you double check if the problem is not present with older app versions?

**Comment by EmilijusS** [comment]
Hello. Sorry for late answer, but I think the problem might be that you need to add `--cap-add=NET_ADMIN` to your `docker run` command (for example `docker run -it --rm --cap-add=NET_ADMIN nordvpn_image`). If that doesn't solve the issue, you might also try adding `--privileged` instead.

Let us know if this helps.

Side note - the Dockerfile you posted seems to be missing `apt install -y nordvpn` between `apt update` and `apt clean` commands.

**Comment by leogaggl** [comment]
Hi @EmilijusS, 

> Hello. Sorry for late answer, but I think the problem might be that you need to add `--cap-add=NET_ADMIN` to your `docker run` command (for example `docker run -it --rm --cap-add=NET_ADMIN nordvpn_image`). If that doesn't solve the issue, you might also try adding `--privileged` instead.

Thanks for the reply! I will test this on a docker image and get back to you. What about the ChromeOS LXD container? Unable to change any startup parameters.

And the thing is that NordVPN used to work without problems on the Linux for ChromeOS. Not sure what has changed recently.

>Side note - the Dockerfile you posted seems to be missing apt install -y nordvpn between apt update and apt clean commands.

That was my fault. I copied and pasted an excerpt of the docker file, which has a couple other installs too that weren't relevant. It is definitely being installed :-)

**Comment by EmilijusS** [comment]
Do older app versions work? Because if not then it's the environment that changed.

Did you test the docker image with additional `run` arguments? The problem with ChromeOS LXD container might be the same - missing permissions. But we don't have experience with such environment so you might need to figure this one by yourself.

**Comment by leogaggl** [comment]
> Hello. Sorry for late answer, but I think the problem might be that you need to add `--cap-add=NET_ADMIN` to your `docker run` command (for example `docker run -it --rm --cap-add=NET_ADMIN nordvpn_image`). If that doesn't solve the issue, you might also try adding `--privileged` instead.

Just to update you and others with the issue. Addin " --cap-add=NET_ADMIN" to the docker run command does indeed fix the problem on Docker. Thank you for that update!

Unfortunately, on the ChromeOS LXD container you do not have the same control.
