### ISSUE TITLE
How do to allow icmp ping from anywhere to linux with nordvpn?

### ISSUE THREAD

**Issue by tm4ig** [NordSecurity/nordvpn-linux#344]
How can I to allow icmp ping from anywhere to my linux host when nordvpn connection is active?
Earlier I have created issue https://github.com/NordSecurity/nordvpn-linux/issues/158 that nordvpn firewall can not be fully disabled and it have not resolved yet.
Nordvpn firewall is blocking icmp even Firewall disabled option is installed.
Now I want to allow icmp ping for my host where nordvpn is using. How can I to do it?
I have tried  nordvpn whitelist add subnet 0.0.0.0/0 command but with this setting nordvpn does not work.

**Comment by mariusSincovici** [comment]
hi
would meshnet and nicknames be a possible option?
In this way the pings would go thru the tunnel and leak.

**Comment by tm4ig** [comment]
I do not not use meshnet. I want that my linux host with nordvpn will be available by ping from everywhere

**Comment by mariusSincovici** [comment]
Then in this case you might need to play with the routing table and the firewall.

Because by default when the VPN is started, the VPN's interface will be used to send the traffic by default. Allowing packets to bypass the tunnel you'll need to have a route for a specific destination or packet type(check the Policy-based routing). And then to configure the firewall to allow those packets. Kind of this is what happens when LAN access is enabled.

But please keep in mind that this are VPN leaks and should be configured with care because other apps might exploit this.

**Comment by tm4ig** [comment]
I do not want allow ping from my host to anywhere outside vpn. I want allow ping from remote hosts to my host.

**Comment by tm4ig** [comment]
after add 
```
iptables -A OUTPUT -t mangle -p icmp --icmp-type 0 -j MARK --set-mark 0xe1f1
iptables -A OUTPUT -t mangle -p icmp --icmp-type 8 -j MARK --set-mark 0xe1f1
```
ping  is working

**Comment by mariusSincovici** [comment]
I'm closing this, if more info is needed from our side let us know.
