### ISSUE TITLE
lan-discovery true does not persist after reboot - Ubuntu 22.04

### ISSUE THREAD

**Issue by sgrseanIT** [NordSecurity/nordvpn-linux#371]
I worked with the very fine support staff on this: conversation Ticket ID is 15990481

I have nordvpn running on ubuntu 22.04 (not in a vm). I've tried nordvpn v1.0.0 and v3.17.4. 

What I think are relevant settings:
autoconnect true
killswitch true
lan-discovery true

I'm also mounting a local network drive via /etc/fstab

On reboot, the lan-discovery true setting seems to not function as expected.

**How I narrowed this down:** 
When I log into the gnome desktop environment it will hang while trying to mount the network drive. If I switch to command line and log in I cannot ping anything on the LAN. If I disable killswitch and disconnect nordvpn, then log out of command line and into gnome, the drive will mount. I can then re-enable killswitch and reconnect nordvpn and the lan-discovery:true setting works as expected until reboot.

This is annoying.

**How I resolved the issue:** 
sudo nordvpn set lan-discovery false
sudo nordvpn allowlist add subnet "mysubnet"

Now on subsequent reboots nordvpn connects as expected and the drive mounts as expected.

Here is an example of another person having this issue, seemingly on a pi: https://www.reddit.com/r/nordvpn/comments/1abm1q0/pi_nords_landiscovery_functionality_does_not/

**Comment by sgrseanIT** [comment]
Amazing, thanks!

**Comment by bduffy1970** [comment]
Lan discovery is working fine for me on Ubuntu 22.04 as well as 24.04.  The problem I'm having is if I have the killswitch set to enabled, my local network drive set up via /etc/fstab isn't accessible.  Then I have to set lan-discovery off and then set lan-discovery on, then do a mount -a in order for the network drive to be accessible again.  As long as I leave killswitch off, everything is fine.

I have a ticket open since Wednesday but communication seems to be sporadic.  Nothing for 10 hours now.

**Comment by mariusSincovici** [comment]
@bduffy1970 yes, unfortunately at the moment there is a bug that killswitch and LAN discovery don't work correctly at startup. It will be fixed in the next release, in the upcoming days.
Until then, as a workaround, you could try to use allow list(whitelist) option instead of LAN discovery, and whitelist your LAN IP range.

**Comment by mariusSincovici** [comment]
Version 3.18.2 was released. This should fix the problem with killswitch and LAN discovery.
I'll close the ticket for now, but feel free to reopen if needed.
